name: Build IPA
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build IPA
        run: |
          cd "ehviewer apple"
          xcodebuild -project "ehviewer apple.xcodeproj" -scheme "ehviewer apple" -configuration Release -sdk iphoneos -derivedDataPath ../build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          cd ../build/Build/Products/Release-iphoneos
          mkdir -p Payload
          cp -r "ehviewer apple.app" Payload/
          zip -r ../../../EhViewer-Apple.ipa Payload
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: EhViewer-Apple-IPA
          path: EhViewer-Apple.ipa
